name: authentication_repository
description: Dart package which manages the authentication domain.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  equatable: ^2.0.3
  firebase_auth: ^3.3.19
  firebase_core: ^1.12.0
  flutter:
    sdk: flutter
  google_sign_in: ^5.3.3
  very_good_analysis: ^2.4.0
  meta: ^1.7.0
  formz: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^0.3.0
  flutter_lints: ^2.0.0
