name: todos_api
description: Dart package which manages the authentication domain.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.5.0
  meta: ^1.7.0
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
